# Use a imagem base oficial do Node.js
FROM node:20

# Crie e defina o diretório de trabalho
WORKDIR /app

# Copie o package.json e package-lock.json (ou yarn.lock) para o diretório de trabalho
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos para o diretório de trabalho
COPY . .

# Compile o TypeScript se necessário
RUN npm run build

# Exponha a porta que o app irá rodar
EXPOSE 3000

# Comando para iniciar o app usando PM2
CMD ["npm", "start"]
